"""Immutable Cart Optimization contract models."""

from app.cart_optimization.orchestrator import CartOptimizationOrchestrator
from app.cart_optimization.quantity_semantics import (
    QuantityResolutionStatus,
    VariantQuantityResolutionService,
    VariantQuantitySemantics,
)
from app.cart_optimization.request_builder import CartOptimizationRequestBuilder
from app.cart_optimization.service import CartOptimizationService
from app.cart_optimization.serialization import CartPlanningSerialization
from app.cart_optimization.persistence import (
    FilesystemPlanningRequestRepository,
    FilesystemPlanningResultRepository,
    PlanningRecordConflict,
    PlanningRecordMalformed,
    PlanningRequestRepository,
    PlanningResultRepository,
)
from app.cart_optimization.construction import (
    CandidateAllocationSet,
    CandidateEnumerationResult,
    CandidateEnumerationStatus,
    CandidatePlanConstructionInput,
    CandidatePlanConstructionService,
)

from app.cart_optimization.enums import (
    ConstraintHardness,
    CoverageState,
    OptimizationOutcome,
    PlanRejectionCode,
    PlanFeasibility,
)
from app.cart_optimization.types import (
    BudgetConstraint,
    CandidatePlan,
    CandidatePlanCoverage,
    CartItemRequest,
    CartOptimizationRequest,
    CartOptimizationResult,
    CheckoutGroup,
    DeliveryPreferenceConstraint,
    EffectiveCostEvaluationReference,
    InconveniencePenaltyConstraint,
    ItemAllocation,
    CandidateItemAllocation,
    CandidateListingProvenance,
    LogicalCart,
    MaximumCheckoutGroupsConstraint,
    MembershipPreferenceConstraint,
    OptimizationConstraintReference,
    PlatformCartGroup,
    RejectedPlan,
    RetailerAllocation,
    RetailerPreferenceConstraint,
    SubstitutionPolicyConstraint,
)

__all__ = [
    "BudgetConstraint",
    "CandidateAllocationSet",
    "CandidateEnumerationResult",
    "CandidateEnumerationStatus",
    "CandidatePlan",
    "CandidatePlanCoverage",
    "CandidatePlanConstructionInput",
    "CandidatePlanConstructionService",
    "CartItemRequest",
    "CartOptimizationRequest",
    "CartOptimizationResult",
    "CartOptimizationOrchestrator",
    "CartOptimizationRequestBuilder",
    "CartOptimizationService",
    "CartPlanningSerialization",
    "FilesystemPlanningRequestRepository",
    "FilesystemPlanningResultRepository",
    "PlanningRecordConflict",
    "PlanningRecordMalformed",
    "PlanningRequestRepository",
    "PlanningResultRepository",
    "CheckoutGroup",
    "ConstraintHardness",
    "CoverageState",
    "DeliveryPreferenceConstraint",
    "EffectiveCostEvaluationReference",
    "InconveniencePenaltyConstraint",
    "ItemAllocation",
    "CandidateItemAllocation",
    "CandidateListingProvenance",
    "LogicalCart",
    "MaximumCheckoutGroupsConstraint",
    "MembershipPreferenceConstraint",
    "OptimizationConstraintReference",
    "OptimizationOutcome",
    "PlanRejectionCode",
    "PlanFeasibility",
    "PlatformCartGroup",
    "QuantityResolutionStatus",
    "RejectedPlan",
    "RetailerAllocation",
    "RetailerPreferenceConstraint",
    "SubstitutionPolicyConstraint",
    "VariantQuantityResolutionService",
    "VariantQuantitySemantics",
]
