"""Immutable contracts for deterministic scrape-job ingestion."""

from app.data_ingestion.enums import (
    AttemptOutcome,
    CaptureType,
    CompletenessState,
    DownstreamMode,
    FailureCategory,
    JobState,
    Platform,
)
from app.data_ingestion.types import (
    AcquisitionResult,
    CaptureCoverage,
    CaptureContext,
    JobCancellation,
    JobFailure,
    LifecycleTransition,
    RawArtifactReference,
    ObservationCompleteness,
    ObservationFieldReference,
    ParsedRetailObservation,
    ParsedRetailObservationBatch,
    ReplayReference,
    RequestParameters,
    ScrapeAttempt,
    ScrapeJob,
    IngestionWorkerResult,
    NormalizedObservation,
)
from app.data_ingestion.observation_registry import (
    InMemoryObservationRegistry,
    FilesystemObservationRegistry,
    ObservationRegistrationConflict,
    ObservationRegistry,
)

__all__ = [
    "AttemptOutcome",
    "AcquisitionResult",
    "CaptureContext",
    "CaptureCoverage",
    "CaptureType",
    "CompletenessState",
    "DownstreamMode",
    "FailureCategory",
    "JobCancellation",
    "JobFailure",
    "JobState",
    "LifecycleTransition",
    "Platform",
    "RawArtifactReference",
    "ObservationCompleteness",
    "ObservationFieldReference",
    "ParsedRetailObservation",
    "ParsedRetailObservationBatch",
    "IngestionWorkerResult",
    "NormalizedObservation",
    "ReplayReference",
    "RequestParameters",
    "ScrapeAttempt",
    "ScrapeJob",
    "InMemoryObservationRegistry",
    "FilesystemObservationRegistry",
    "ObservationRegistrationConflict",
    "ObservationRegistry",
]
