"""Frozen vocabulary for the data-ingestion contract layer."""

from enum import StrEnum


class Platform(StrEnum):
    BLINKIT = "BLINKIT"
    ZEPTO = "ZEPTO"
    INSTAMART = "INSTAMART"
    BIGBASKET = "BIGBASKET"
    FLIPKART_MINUTES = "FLIPKART_MINUTES"


class CaptureType(StrEnum):
    SEARCH_RESULTS = "SEARCH_RESULTS"
    PRODUCT_DETAIL = "PRODUCT_DETAIL"
    CART = "CART"
    CHECKOUT = "CHECKOUT"
    DELIVERY_SLOTS = "DELIVERY_SLOTS"


class FailureCategory(StrEnum):
    NETWORK_ERROR = "NETWORK_ERROR"
    REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
    BROWSER_TIMEOUT = "BROWSER_TIMEOUT"
    HTTP_403 = "HTTP_403"
    CAPTCHA_OR_ANTI_BOT = "CAPTCHA_OR_ANTI_BOT"
    HTTP_404 = "HTTP_404"
    PARSER_RUNTIME_FAILURE = "PARSER_RUNTIME_FAILURE"
    PARSER_LAYOUT_CHANGE = "PARSER_LAYOUT_CHANGE"
    MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS"
    MALFORMED_HTML_OR_JSON = "MALFORMED_HTML_OR_JSON"
    NORMALIZATION_RUNTIME_FAILURE = "NORMALIZATION_RUNTIME_FAILURE"
    NORMALIZATION_CONTRACT_FAILURE = "NORMALIZATION_CONTRACT_FAILURE"
    STORAGE_FAILURE = "STORAGE_FAILURE"
    OBSERVATION_REGISTRATION_FAILURE = "OBSERVATION_REGISTRATION_FAILURE"
    PIPELINE_PUBLICATION_FAILURE = "PIPELINE_PUBLICATION_FAILURE"
    WORKER_CRASH = "WORKER_CRASH"
    QUEUE_LEASE_EXPIRY = "QUEUE_LEASE_EXPIRY"
    CANCELLATION = "CANCELLATION"
    MALFORMED_REQUEST = "MALFORMED_REQUEST"
    UNSUPPORTED_PLATFORM = "UNSUPPORTED_PLATFORM"
    UNSUPPORTED_CAPTURE_TYPE = "UNSUPPORTED_CAPTURE_TYPE"
    EMPTY_RESULTS_WITH_COMPLETENESS_EVIDENCE = "EMPTY_RESULTS_WITH_COMPLETENESS_EVIDENCE"
    EMPTY_RESULTS_WITHOUT_COMPLETENESS_EVIDENCE = "EMPTY_RESULTS_WITHOUT_COMPLETENESS_EVIDENCE"
    EXPIRED_QUEUED_JOB = "EXPIRED_QUEUED_JOB"
    EXPIRED_RUNNING_LEASE = "EXPIRED_RUNNING_LEASE"


class AttemptOutcome(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    INVALID = "INVALID"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    DEAD_LETTERED = "DEAD_LETTERED"


class DownstreamMode(StrEnum):
    NONE = "NONE"
    PRODUCT_INTELLIGENCE = "PRODUCT_INTELLIGENCE"
    COST_INTELLIGENCE = "COST_INTELLIGENCE"
    CART_OPTIMIZATION = "CART_OPTIMIZATION"
    FULL_PIPELINE = "FULL_PIPELINE"


class JobState(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    DEQUEUED = "DEQUEUED"
    ACQUIRING = "ACQUIRING"
    ARTIFACT_CAPTURED = "ARTIFACT_CAPTURED"
    PARSING = "PARSING"
    PARSED = "PARSED"
    NORMALIZING = "NORMALIZING"
    NORMALIZED = "NORMALIZED"
    REGISTERING_OBSERVATION = "REGISTERING_OBSERVATION"
    REGISTERED = "REGISTERED"
    PUBLISHING_PIPELINE_EVENT = "PUBLISHING_PIPELINE_EVENT"
    COMPLETED = "COMPLETED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    DEAD_LETTERED = "DEAD_LETTERED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    INVALID = "INVALID"
